# Dependencies

highlighter:      pygments
baseurl:          /

# Permalinks
permalink:        pretty


# Setup
title:            Thejas Kumar Gangadhar
tagline:          'My Blog'
description:      'Tech Enthusiast | Software Developer'
url:              http://hyde.getpoole.com


author:
  name:           'Thejas Kumar'
  twitter:        'https://twitter.com/thejasg13'
  github:         'http://github.com/thejasgit'
  linkedin:       'https://www.linkedin.com/in/thejaskumar'
  email:          'tgangadh@usc.edu'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
